#!/usr/bin/env python3
"""Generated-output drift gate (spec #60).

Regenerates both themes into a temp location and compares byte-for-byte with
the committed theme directories. Exits non-zero on any drift.

CI usage:
    python tools/writer2027-icons/build_themes.py --source-cache <pinned-cache>
    git diff --exit-code -- icon-themes/writer2027_carbon_svg icon-themes/writer2027_phosphor_svg
"""

import argparse
import filecmp
import shutil
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_themes  # noqa: E402
import burn_ai_icons  # noqa: E402

THEMES = ("carbon", "phosphor", "tdesign")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source-cache", type=Path,
                    default=REPO / ".work" / "icon-sources")
    ap.add_argument("--keep", action="store_true",
                    help="keep the temp regeneration dir on failure")
    args = ap.parse_args(argv)

    lock = build_themes.load_lock(build_themes.LOCK_FILE)
    cache = build_themes.check_source(lock, args.source_cache, fetch=False)

    with tempfile.TemporaryDirectory(prefix="w2027-drift-") as tmp:
        tmp_path = Path(tmp)
        for theme in THEMES:
            # Recreate the committed layout: icon-themes/<theme_dir_name>/
            out = tmp_path / build_themes.THEMES[theme]
            if theme == "tdesign":
                mapping = build_themes.load_yaml(
                    build_themes.TOOLS_DIR / "icon-map-tdesign.yaml")
            else:
                mapping = build_themes.load_yaml(build_themes.MAP_FILE)
            build_themes.build_theme(theme, mapping, cache, lock, out)
        # Burn the AI icon set into the fresh themes dir (same as production).
        burn_ai_icons.main(["--themes-dir", str(tmp_path)])
        drift = []
        for theme in THEMES:
            committed = REPO / "icon-themes" / build_themes.THEMES[theme]
            fresh = tmp_path / build_themes.THEMES[theme]
            # Compare the build-consumed assets (cmd/ + links.txt); the
            # GENERATED.json manifest is provenance metadata regenerated by
            # build_themes.py main() and is not part of the byte-drift gate.
            for sub in ("cmd", "links.txt"):
                c = committed / sub
                f = fresh / sub
                if sub == "cmd":
                    c_comp = filecmp.dircmp(c, f)
                    if c_comp.left_only or c_comp.right_only or c_comp.diff_files:
                        drift.append(f"{theme}/{sub}")
                        print(f"DRIFT in {theme}/{sub}:")
                        for x in c_comp.left_only:
                            print(f"  only in committed: {x}")
                        for x in c_comp.right_only:
                            print(f"  only in fresh: {x}")
                        for x in c_comp.diff_files:
                            print(f"  differs: {x}")
                else:
                    if c.read_bytes() != f.read_bytes():
                        drift.append(f"{theme}/{sub}")
                        print(f"DRIFT in {theme}/{sub}: content differs")
        if drift:
            print(f"FAIL: drift in {drift}", file=sys.stderr)
            if args.keep:
                print(f"regenerated output kept at {tmp_path}")
            return 1
        print("PASS: committed themes match generator output")
        return 0


if __name__ == "__main__":
    sys.exit(main())