#!/usr/bin/env python3
# WriterAgent - AI Writing Assistant for LibreOffice
# Copyright (c) 2026 KeithCu
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""Installer and verification helper for FizzBee formal model checker.

Usage:
    python scripts/install_fizzbee.py --check
    python scripts/install_fizzbee.py --install

GitHub assets are named ``fizzbee-<tag>-linux_x86.tar.gz`` (not ``amd64``).
The tarball is a tree: ``fizz`` wrapper, ``fizzbee`` Go binary, ``parser/``.
Copying the first file whose name starts with ``fizz`` used to install
generated protobuf Python (``fizz_ast_pb2.py``), which ``make check-fizzbee``
then tried to execute as a shell script.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import stat
import sys
import tarfile
import tempfile
import urllib.request
from typing import Any, Iterable


_PROTOBUF_MARKER = b"Generated by the protocol buffer compiler"
_ELF = b"\x7fELF"
_MACHO_BE = b"\xca\xfe\xba\xbe"
_MACHO_64 = b"\xcf\xfa\xed\xfe"
_MACHO_64_BE = b"\xfe\xed\xfa\xcf"


def get_venv_bin_dir() -> str:
    """Get the active virtual environment bin directory or fallback to ~/.local/bin."""
    if hasattr(sys, "real_prefix") or (hasattr(sys, "base_prefix") and sys.base_prefix != sys.prefix):
        return os.path.join(sys.prefix, "bin" if sys.platform != "win32" else "Scripts")
    return os.path.expanduser("~/.local/bin")


def get_venv_share_dir() -> str:
    """Directory that holds the extracted FizzBee release tree."""
    if hasattr(sys, "real_prefix") or (hasattr(sys, "base_prefix") and sys.base_prefix != sys.prefix):
        return os.path.join(sys.prefix, "share", "fizzbee")
    return os.path.expanduser("~/.local/share/fizzbee")


def release_platform_token(system: str | None = None, machine: str | None = None) -> str:
    """Map Python platform names to FizzBee asset tokens (linux_x86, macos_arm, …)."""
    system = (system or platform.system()).lower()
    machine = (machine or platform.machine()).lower()
    arm = machine in ("arm64", "aarch64")
    if system == "linux":
        return "linux_arm" if arm else "linux_x86"
    if system in ("darwin", "macos"):
        return "macos_arm" if arm else "macos_x86"
    raise ValueError(f"Unsupported OS for automated install: {system}")


def select_release_asset(assets: Iterable[dict[str, Any]], plat: str) -> dict[str, Any] | None:
    """Pick the platform tarball; never fall back to source zip or the first asset."""
    needle = f"-{plat}.tar.gz"
    for asset in assets:
        name = str(asset.get("name", "")).lower()
        if name.startswith("fizzbee-") and name.endswith(needle):
            return asset
    return None


def is_fizzbee_cli(path: str) -> bool:
    """True for the ``fizz`` wrapper or native ``fizzbee`` binary; false for protobuf stubs."""
    base = os.path.basename(path)
    if base not in ("fizz", "fizzbee", "fizz.exe", "fizzbee.exe"):
        return False
    if path.endswith(".py"):
        return False
    try:
        with open(path, "rb") as fh:
            head = fh.read(256)
    except OSError:
        return False
    if _PROTOBUF_MARKER in head:
        return False
    if head.startswith(_ELF) or head.startswith(_MACHO_BE) or head.startswith(_MACHO_64) or head.startswith(_MACHO_64_BE):
        return True
    return head.startswith(b"#!")


def find_cli_in_tree(root: str) -> str | None:
    """Prefer the top-level ``fizz`` wrapper, then a native ``fizzbee`` binary."""
    preferred: list[tuple[int, str]] = []
    fallback: list[tuple[int, str]] = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            path = os.path.join(dirpath, name)
            if not is_fizzbee_cli(path):
                continue
            rel_depth = path[len(root) :].count(os.sep)
            if name in ("fizz", "fizz.exe"):
                preferred.append((rel_depth, path))
            else:
                fallback.append((rel_depth, path))
    preferred.sort()
    fallback.sort()
    if preferred:
        return preferred[0][1]
    if fallback:
        return fallback[0][1]
    return None


def find_fizzbee_binary() -> str | None:
    """Check if a real FizzBee CLI is on PATH or in the venv."""
    candidates = [
        os.path.join(get_venv_bin_dir(), "fizz"),
        os.path.join(get_venv_bin_dir(), "fizzbee"),
        os.path.join(get_venv_bin_dir(), "fizz.exe"),
        os.path.join(get_venv_bin_dir(), "fizzbee.exe"),
    ]
    which = shutil.which("fizz") or shutil.which("fizzbee")
    if which:
        candidates.append(which)
    for path in candidates:
        if path and os.path.isfile(path) and os.access(path, os.X_OK) and is_fizzbee_cli(path):
            return path
    return None


def check_status() -> int:
    """Check if FizzBee is installed and print status."""
    bin_path = find_fizzbee_binary()
    if bin_path:
        print(f"FizzBee binary found at: {bin_path}")
        return 0
    print("FizzBee is NOT currently installed (or .venv/bin/fizzbee is not the CLI).")
    print("\nTo install FizzBee:")
    print("  1. Automated: python scripts/install_fizzbee.py --install")
    print("  2. macOS (Homebrew): brew tap fizzbee-io/fizzbee && brew install fizzbee")
    print("  3. Manual: Download from https://github.com/fizzbee-io/fizzbee/releases")
    return 1


def _link_cli(cli_path: str, dest_dir: str) -> str:
    os.makedirs(dest_dir, exist_ok=True)
    mode = os.stat(cli_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
    os.chmod(cli_path, mode)
    dest_fizz = os.path.join(dest_dir, "fizz")
    dest_fizzbee = os.path.join(dest_dir, "fizzbee")
    for dest in (dest_fizz, dest_fizzbee):
        if os.path.lexists(dest):
            os.remove(dest)
        os.symlink(cli_path, dest)
        os.chmod(dest, mode)
    return dest_fizzbee


def install_fizzbee() -> int:
    """Download and install the FizzBee release tree into the venv."""
    try:
        plat = release_platform_token()
    except ValueError as exc:
        print(str(exc))
        print("Please download manually from https://github.com/fizzbee-io/fizzbee/releases")
        return 1

    print(f"Detecting latest FizzBee release for {plat}...")
    api_url = "https://api.github.com/repos/fizzbee-io/fizzbee/releases/latest"
    req = urllib.request.Request(api_url, headers={"User-Agent": "WriterAgent-Installer"})

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as exc:
        print(f"Failed to query GitHub releases: {exc}")
        print("Fallback download: https://github.com/fizzbee-io/fizzbee/releases")
        return 1

    target_asset = select_release_asset(data.get("assets") or [], plat)
    if not target_asset:
        print(f"No suitable binary release asset found for {plat} in {data.get('tag_name')}")
        return 1

    download_url = target_asset["browser_download_url"]
    asset_name = target_asset["name"]
    print(f"Downloading {asset_name} from {download_url}...")

    dest_dir = get_venv_bin_dir()
    share_dir = get_venv_share_dir()
    os.makedirs(dest_dir, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp_dir:
        archive_path = os.path.join(tmp_dir, asset_name)
        urllib.request.urlretrieve(download_url, archive_path)

        extract_root = os.path.join(tmp_dir, "extracted")
        os.makedirs(extract_root)
        if asset_name.endswith(".tar.gz") or asset_name.endswith(".tgz"):
            with tarfile.open(archive_path, "r:gz") as tar:
                try:
                    tar.extractall(path=extract_root, filter="data")
                except TypeError:
                    tar.extractall(path=extract_root)
        else:
            print(f"Unsupported archive type: {asset_name}")
            return 1

        cli_path = find_cli_in_tree(extract_root)
        if cli_path is None:
            print("Could not find fizz / fizzbee CLI inside archive (refusing protobuf stubs).")
            return 1

        if os.path.isdir(share_dir):
            shutil.rmtree(share_dir)
        os.makedirs(os.path.dirname(share_dir), exist_ok=True)
        # Keep the directory that contains the wrapper (parser/ is a sibling).
        tree_root = os.path.dirname(cli_path)
        shutil.copytree(tree_root, share_dir)
        installed_cli = os.path.join(share_dir, os.path.basename(cli_path))
        dest_path = _link_cli(installed_cli, dest_dir)

    print(f"Successfully installed FizzBee to: {dest_path} (tree: {share_dir})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Install and check FizzBee formal verification tool")
    parser.add_argument("--check", action="store_true", help="Check if FizzBee is currently installed")
    parser.add_argument("--install", action="store_true", help="Download and install FizzBee into .venv/bin")
    args = parser.parse_args()

    if args.install:
        return install_fizzbee()
    return check_status()


if __name__ == "__main__":
    sys.exit(main())
